version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "smallkirby"
    groups:
      all:
        patterns:
          - "*"
